version: "3.2"
services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"