name: CI

on:
  push:
    branches: [ main ]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          command: build
  rustfmt:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sourves
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

    